sudo: required
services:
    - docker

before_install:
    - docker build -t moaz/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true moaz/react-test npm test

after_success:
    - docker build -t moaz/multi-client ./client
    - docker build -t moaz/multi-nginx ./nginx
    - docker build -t moaz/multi-server ./server
    - docker build -t moaz/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push moaz/multi-client 
    - docker push moaz/multi-nginx   
    - docker push moaz/multi-server  
    - docker push moaz/multi-worker  