sudo: required
services:
    - docker

before_install:
    - docker build -t moazgalbat/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true moazgalbat/react-test npm test

after_success:
    - docker build -t moazgalbat/multi-client ./client
    - docker build -t moazgalbat/multi-nginx ./nginx
    - docker build -t moazgalbat/multi-server ./server
    - docker build -t moazgalbat/multi-worker ./worker
    - echo "$DOCKEr_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push moazgalbat/multi-client 
    - docker push moazgalbat/multi-nginx   
    - docker push moazgalbat/multi-server  
    - docker push moazgalbat/multi-worker  